name: Update from minecraft-data

on:
  workflow_dispatch:
    inputs:
      new_mc_version:
        description: New minecraft version number
        required: true
        type: string
      mcdata_branch:
        description: minecraft-data branch for this version
        required: true
        type: string
      mcdata_pr_url:
        description: minecraft-data PR number to open a PR here against
        required: false
        default: ''
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install gh-helpers

    - name: Run updator script
      run: node .github/helper/updator.js
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD || secrets.GITHUB_TOKEN }}
        MCDATA_BRANCH: ${{ github.event.inputs.mcdata_branch }}
        MCDATA_PR_URL: ${{ github.event.inputs.mcdata_pr_url }}
        NEW_MC_VERSION: ${{ github.event.inputs.new_mc_version }}
